export enum MagicLinkStatusEnum {
    NOT_FOUND = 'NOT_FOUND',
    EXPIRED = 'EXPIRED',
    CONFIRMED = 'CONFIRMED',
    PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
    ALREADY_CONFIRMED = 'ALREADY_CONFIRMED',
}
